# Generated by Django 4.1.1 on 2023-05-06 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyCourse', models.CharField(max_length=255, null=True)),
                ('studyPreference', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=400, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(null=True)),
                ('post_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.post')),
            ],
        ),
        migrations.CreateModel(
            name='StudyBuddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(null=True)),
                ('post_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('computing_id', models.CharField(max_length=20, null=True, unique=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('profile_picture', models.ImageField(default='/profile_pictures/default_pic.jpg', upload_to='profile_pictures')),
                ('phone_number', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('current_year', models.CharField(max_length=20, null=True)),
                ('gender_visible', models.BooleanField(default=False)),
                ('phone_visible', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
