# Generated by Django 4.1.1 on 2023-02-19 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=255, null=True, unique=True)),
                ('course_section', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('units', models.CharField(max_length=255, null=True)),
                ('catalog_number', models.CharField(max_length=255, null=True)),
                ('instructor_first_name', models.CharField(max_length=255, null=True)),
                ('instructor_last_name', models.CharField(max_length=255, null=True)),
                ('instructor_email', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('studyCourse', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('publish_date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='current_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.profile')),
                ('post_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.post')),
            ],
        ),
        migrations.CreateModel(
            name='StudyBuddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.profile')),
                ('post_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.post')),
            ],
        ),
    ]
