# Generated by Django 4.1.1 on 2023-04-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0002_course_post_profile_current_year_profile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studybuddy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='owner',
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studybuddy.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='studyPreference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
