# Generated by Django 4.1.1 on 2023-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0003_remove_studybuddy_owner_remove_studygroup_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/profile_pictures/default_profile_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
