# Generated by Django 4.1.1 on 2023-04-13 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
